packages:
  remote_package_files:
    url: https://github.com/plains203/skyfandc
    files: 
      - sensor_power_fan.yaml
      - sensor_power_light.yaml
      - tuya_fan.yaml
      - tuya_light.yaml

substitutions:
  device_name: sky-fan
  device_friendly_name: sky_fan
  fan_name: skyfan-skyfan
  light_name: skyfan-ceilinglight
  skyfan_model: "SKY1203"
  temp_name: C6 Temp
  wifi_signal_name: C6 WiFi Signal
  wifi_percent_name: C6 WiFi Strength
  cpu_temp: C6 CPU Temp
  uptime: C6 Uptime

esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name} 
  name_add_mac_suffix: true
  project:
    name: Shaun.SkyFanDC
    version: "0.1"
  on_boot:
    priority: -100  # Run after everything else
    then:
      - delay: 2s  # Give I2C time to settle
      
esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

api:

# Logger not using the serial port as tuya needs it
logger:
  baud_rate: 0

i2c:
  sda: 22
  scl: 23
  scan: true

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
    
captive_portal:

esp32_ble_tracker:
  scan_parameters:
    continuous: True
    active: True
    interval: 320ms
    window: 300ms

bluetooth_proxy:
  active: True  # allows outbound connections from HA to devices.

uart:
  rx_pin: 3
  tx_pin: 2
  baud_rate: 9600
  
tuya:
  id: tuyamcu 

sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: $wifi_signal_name
    id: wifi_signal_db
    update_interval: 60s
    entity_category: diagnostic

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: $wifi_percent_name
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: diagnostic

  - platform: internal_temperature
    name: $cpu_temp
    entity_category: diagnostic

  - platform: uptime
    name: $uptime
    entity_category: diagnostic
